version: '3.8'
services:
  patient-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: patientdb
    ports:
      - "3307:3306"
    volumes:
      - .init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

    container_name: patient-db
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: note
    ports:
      - "27018:27017"
    volumes:
        - ./init.js:/docker-entrypoint-initdb.d/init-mongo.js
        - mongo_data:/data/db
    container_name: mongo

  mediscreen:
    build: ./ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:9101
      patientUrl: http://patient-api:8081/patient
      noteUrl: http://note-api:8082/note
      assessmentUrl: http://note-api:8082/assess
    depends_on:
      - config-server
      - note-api
      - patient-api
    container_name: mediscreen

  config-server:
    build: ./config-server
    restart: always
    ports:
      - "9101:9101"
    container_name: config-server

  patient-api:
    build: ./patient
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_PW: password
      DB_USER: root
      DB_HOST: patient-db
      DB_PORT: 3306
      DB_NAME: patientdb
      SPRING_CLOUD_CONFIG_URI: http://config-server:9101
    depends_on:
      - patient-db
      - config-server
    container_name: patient-api

  note-api:
    build: ./note
    restart: always
    ports:
      - "8082:8082"
    environment:
      MONGO_USER: root
      MONGO_PW: root
      MONGO_HOST: mongo
      MONGO_PORT: 27018
      MONGO_AUTH2: ?authSource=admin
      SPRING_CLOUD_CONFIG_URI: http://config-server:9101
    depends_on:
      - mongo
      - config-server
      - patient-api
    container_name: note-api

volumes:
    db_data:
    mongo_data:


