version: '3.8'
services:
  patient_db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: password
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: patientdb
    ports:
      - "3307:3306"
    volumes:
      - .script.sql:/docker-entrypoint-initdb.d/script.sql

    container_name: patient_db
  note:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
        - ./init.js:/docker-entrypoint-initdb.d/init-mongo.js
    container_name: note

  mediscreen:
    build: ./ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:9101
      patientUrl: http://patient_api:8081/patient
      notUrl: http://note_api:8082/note
    depends_on:
      - config-server
      - note_api
      - patient_api
    container_name: mediscreen

  config-server:
    build: ./config-server
    restart: always
    ports:
      - "9101:9101"
    container_name: config-server

  patient_api:
    build: ./patient
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_USERNAME: password
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://patient_db:3306/patientdb?useSSL=false
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: true
      SPRING_CLOUD_CONFIG_URI: http://config-server:9101
    depends_on:
      - patient_db
      - config-server
    container_name: patient_api

  note_api:
    build: ./note
    restart: always
    ports:
      - "8082:8082"
    environment:
      spring_data_mongodb_uri: mongodb://note:27017
      spring_data_mongodb_database: note
      spring_data_mongodb_username: root
      spring_data_mongodb_password: root
      SPRING_CLOUD_CONFIG_URI: http://config-server:9101
    depends_on:
      - note
      - config-server
      - patient_api
    container_name: note_api
